compitiondemande_index:
    path:     /
    defaults: { _controller: "CompetitionBundle:Compitiondemande:index" }
    methods:  GET

compitiondemande_show:
    path:     /{id}/show
    defaults: { _controller: "CompetitionBundle:Compitiondemande:show" }
    methods:  GET

compitiondemande_new:
    path:     /new
    defaults: { _controller: "CompetitionBundle:Compitiondemande:new" }
    methods:  [GET, POST]

compitiondemande_edit:
    path:     /{id}/edit
    defaults: { _controller: "CompetitionBundle:Compitiondemande:edit" }
    methods:  [GET, POST]

compitiondemande_delete:
    path:     /{id}/delete
    defaults: { _controller: "CompetitionBundle:Compitiondemande:delete" }
