dmoffre_index:
    path:     /
    defaults: { _controller: "CompetitionBundle:dmoffre:index" }
    methods:  GET

dmoffre_show:
    path:     /{id}/show
    defaults: { _controller: "CompetitionBundle:dmoffre:show" }
    methods:  GET

dmoffre_new:
    path:     /new
    defaults: { _controller: "CompetitionBundle:dmoffre:new" }
    methods:  [GET, POST]

dmoffre_edit:
    path:     /{id}/edit
    defaults: { _controller: "CompetitionBundle:dmoffre:edit" }
    methods:  [GET, POST]

dmoffre_delete:
    path:     /{id}/delete
    defaults: { _controller: "CompetitionBundle:dmoffre:delete" }
    methods:  DELETE
