offres_index:
    path:     /
    defaults: { _controller: "CompetitionBundle:Offres:index" }
    methods:  GET

offres_show:
    path:     /{idOffre}/show
    defaults: { _controller: "CompetitionBundle:Offres:show" }
    methods:  GET

offres_new:
    path:     /new
    defaults: { _controller: "CompetitionBundle:Offres:new" }
    methods:  [GET, POST]

offres_edit:
    path:     /{idOffre}/edit
    defaults: { _controller: "CompetitionBundle:Offres:edit" }
    methods:  [GET, POST]

offres_delete:
    path:     /{idOffre}/delete
    defaults: { _controller: "CompetitionBundle:Offres:delete" }
    methods:  DELETE
