admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_competition:
    resource: "@AdminBundle/Resources/config/routing/competitions.yml"
    prefix:   /competition

admin_compitiondemande:
    resource: "@AdminBundle/Resources/config/routing/compitiondemande.yml"
    prefix:   /compitiondemande
