<?php

namespace CompetitionBundle\Repository;

/**
 * ompitiondemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompitiondemandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByNom($nom)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT a from CompetitionBundle:Compitiondemande a where a.competitiontitre LIKE '$nom%' ");
        return $query->getResult();
    }
}
