<?php

namespace CompetitionBundle\Repository;

/**
 * dmoffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dmoffreRepository extends \Doctrine\ORM\EntityRepository
{
}
